version: '3.1'

networks:
    test:
        driver: bridge

services:
    server:
        image: server:latest
        ports: 
           - "3000:3000"
        networks:
            - test

    waf:
        image: waf:latest
        ports: 
          - "3001:3001"
        networks:
            - test


