version: '3.1'

# networks: 
#     test:
#         driver: bridge

services:
    server:
        image: server:v01
        ports: 
           - "3000:3000"
        depends_on: 
            - mongo
        # networks:
        #     - test
    waf:
        image: waf:v01
        ports: 
          - "3001:3001"
        depends_on: 
            - server
        # networks:
        #     - test
    mongo:
        image: mongo:4.4.2
        volumes: 
           - mongodata:/data/db
        ports:
          - "27017:27017"
        # networks:
        #     - test

volumes: 
    mongodata:


